### ISSUE TITLE
Unable to disable

### ISSUE THREAD

**Issue by Nicolab** [francodacosta/atom-function-name-status-bar#1]
Hello,

Atom crash when disable the package. The error:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at window.onload (file:///opt/atom/resources/app/static/index.js:6:29) index.js:29
window.onload index.js:29
```

Ubuntu 14.04
Atom 0.108

Edit: it may be necessary to add the method unserialize () to your package

**Comment by wayou** [comment]
same problem here

**Comment by francodacosta** [comment]
@Nicolab @wayou I'm a bit busy now, but i will take a look into that soon

**Comment by sankargorthi** [comment]
What worked for me:
1. Clicked on disable
2. Restart Atom
3. Uninstall

**Comment by francodacosta** [comment]
@Nicolab @wayou  @sankargorthi 

sorry to take so long, this should be fixed now, you need to update the package and restart atom.

Disabling or reloading the package should work fine after that

**Comment by Nicolab** [comment]
Thanks
