### ISSUE TITLE
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

### ISSUE THREAD

**Issue by rdccosmo** [francodacosta/atom-function-name-status-bar#2]
Hi,

After I installed the package it keeps giving me this error at
.atom/packages/function-name-in-status-bar/lib/function-name-status-bar.coffee:15

Any ideas?

**Comment by egyptianbman** [comment]
I'm having this issue as well:

![image](https://cloud.githubusercontent.com/assets/323600/5291999/b47a7322-7b20-11e4-8258-e4573ed748b6.png)

**Comment by francodacosta** [comment]
@rdccosmo @egyptianbman I will have a look at it soon

**Comment by francodacosta** [comment]
@rdccosmo @egyptianbman what language are you developing in ?

**Comment by egyptianbman** [comment]
php

**Comment by francodacosta** [comment]
@rdccosmo @egyptianbman 

should be fixed now,  can you update and confirm? (you will need to restart atom)

**Comment by egyptianbman** [comment]
@francodacosta Thank you, it's not crashing anymore.  Using a dark theme however, the text remains black while the rest of the text in the status bar is a lighter color.  I wasn't sure if it was working or not until I switched to a light theme, then was able to see the `@ functionName`.

**Comment by francodacosta** [comment]
@egyptianbman it seems to work great for atom dark theme

You can change the color by styling the element

just add the following to `~/.atom/styles.less`

``` css
.current-path .function-info {
    /* your css styles here*/
}
```

**Comment by egyptianbman** [comment]
Thanks!
